import { Inter } from "next/font/google";
import "./globals.css";
// import style from './globals.css'
import Navbar from "./components/Navbar/Navbar";
import Footer from "./components/Footer/Footer";
import { ThemeContextProvider } from "@/context/ThemeContex";
// import AuthProvider from "../AuthProvider/AuthProvider";
import AuthProvider from "@/AuthProvider/AuthProvider";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "nahiyanDev",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeContextProvider>
          <AuthProvider>
            <div style={{
              minHeight: "100vh",
              maxWidth: '1366px',
              margin: "0 auto",
              display: "flex",
              flexDirection: "column",
              justifyContent: "space-between",

            }} >
              <Navbar />
              {children}
              <Footer />
            </div>
          </AuthProvider>
        </ThemeContextProvider>
      </body>
    </html>
  );
}
